services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: api
    volumes:
      - ./:/app:delegated
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis

    restart: on-failure

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
   

  celery:
    build: .
    container_name: celery_worker
    command: celery -A celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  flower:
    build: .
    command: celery -A celery_worker.celery_app flower --port=5555
    ports:
    - "5555:5555"
    depends_on:
    - redis
    env_file:
    - .env
    volumes:
    - .:/app


  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres-data:
  pgadmin-data:
  redis-data:
