export const products = [
    {
      id: "1",
      title: "TOZO T6 True Wireless Earbuds Bluetooth Headphones",
      price: 70,
      rating: 4.5,
      reviews: 738,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-J7KCU9yZXyUDbs52YrpM9kq3u7Uefr.png",
      badge: "HOT" as const,
    },
    {
      id: "2",
      title: "Samsung Electronics Samsung Galaxy S21 5G",
      price: 2300,
      rating: 4.8,
      reviews: 526,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-J7KCU9yZXyUDbs52YrpM9kq3u7Uefr.png",
    },
    {
      id: "3",
      title: "Amazon Basics High-Speed HDMI Cable (18 Gbps, 4K/60Hz)",
      price: 360,
      rating: 4.7,
      reviews: 423,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-J7KCU9yZXyUDbs52YrpM9kq3u7Uefr.png",
      badge: "BEST DEALS" as const,
    },
    {
      id: "4",
      title: "Apple MacBook Pro 13-inch",
      price: 1299,
      rating: 4.9,
      reviews: 312,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-J7KCU9yZXyUDbs52YrpM9kq3u7Uefr.png",
      badge: "NEW" as const,
    },
    {
      id: "5",
      title: "Sony WH-1000XM4 Wireless Noise-Canceling Over-Ear Headphones",
      price: 348,
      rating: 4.6,
      reviews: 1024,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-J7KCU9yZXyUDbs52YrpM9kq3u7Uefr.png",
      badge: "TOP RATED" as const,
    },
    {
      id: "6",
      title: "Nikon D3500 W/ AF-P DX NIKKOR 18-55mm f/3.5-5.6G VR",
      price: 496,
      rating: 4.8,
      reviews: 215,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-J7KCU9yZXyUDbs52YrpM9kq3u7Uefr.png",
    },
  ]