"""db migrate

Revision ID: cd2cdb335e90
Revises: 4bd138c7e55b
Create Date: 2025-04-29 03:01:00.542644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2cdb335e90'
down_revision: Union[str, None] = '4bd138c7e55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('order_items', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'phone')
    op.drop_column('order_items', 'address')
    # ### end Alembic commands ###
